Fixed a bug with ignoring `cpPkg` and `cpCompiler` fields.
commercialhaskell/stack pull request #5597
Opened 2021-08-02 10:58 UTC by Haskell-mouse

It looks like a user can't override location `ghc` and `ghc-pkg`, because these options are ignored in  `ensureConfig`. 
I prefer to keep `findExecutable` checking and I've just removed obviously mistaken adding "--with-ghc/ghc-pkg=" to the path.

2021-08-09 03:50 UTC, snoyberg requested changes
Looks great, thanks! Would you mind adding a ChangeLog entry for this bug fix?

2021-08-09 22:02 UTC, Haskell-mouse commented
> Looks great, thanks! Would you mind adding a ChangeLog entry for this bug fix?

Thanks. I've added a short note to the `Bug fixes` section.

2021-08-10 02:24 UTC, snoyberg approved these changes

2021-08-10 04:29 UTC, merged

2021-08-10 04:29 UTC, snoyberg commented
Thanks!